<?php

namespace App\Models;

use App\Models\Concerns\BelongsToCompany;
use Database\Factories\SocialSecurityContributionFactory;
use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * A single social-security contribution row, generated by the payroll
 * engine for one employee/entity/concept/sub-range within a PayrollEntry's
 * settlement. Per .ai/05-DATABASE.md, this table is "INMUTABLE... sigue las
 * reglas de payroll_entries" — and PayrollEntry/PayrollEntryLine (Fase 9)
 * are themselves AJUSTE tables with no ORM-level immutability guard, only
 * service-layer discipline (see PayrollEntry's own docblock). Building a
 * third, duplicated guard class here for social_security_contributions
 * would contradict that same cross-reference, so this model intentionally
 * has none either: it stays freely recalculable while the parent
 * payroll_period is not 'closed', enforced at the service layer
 * (App\Services\Payroll\PayrollCalculationService), never by the model.
 */
class SocialSecurityContribution extends Model
{
    /** @use HasFactory<SocialSecurityContributionFactory> */
    use BelongsToCompany, HasFactory, HasUuids;

    /**
     * @var list<string>
     */
    protected $fillable = [
        'company_id',
        'payroll_entry_id',
        'entity_id',
        'concept_id',
        'period_from',
        'period_to',
        'base_amount',
        'employee_amount',
        'employer_amount',
    ];

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'period_from' => 'date:Y-m-d',
            'period_to' => 'date:Y-m-d',
            'base_amount' => 'decimal:2',
            'employee_amount' => 'decimal:2',
            'employer_amount' => 'decimal:2',
        ];
    }

    /**
     * @return BelongsTo<PayrollEntry, $this>
     */
    public function payrollEntry(): BelongsTo
    {
        return $this->belongsTo(PayrollEntry::class);
    }

    /**
     * SocialSecurityEntity is a DIRECTO/GLOBAL model (nullable company_id,
     * platform-default rows possible via HasPlatformOrCompanyDefault).
     * Eager-loading this relation without `->withoutGlobalScope('company')`
     * silently drops any platform-default entity behind the active
     * tenant's BelongsToCompany scope. This exact bug has already bitten
     * three times in Fase 8-9 (see composed-knitting-dusk.md's "Modelos"
     * section) — do not eager-load this relation bare.
     *
     * @return BelongsTo<SocialSecurityEntity, $this>
     */
    public function entity(): BelongsTo
    {
        return $this->belongsTo(SocialSecurityEntity::class);
    }

    /**
     * SocialSecurityConceptDefinition is a DIRECTO/GLOBAL model (nullable
     * company_id, platform-default rows possible via
     * HasPlatformOrCompanyDefault). Eager-loading this relation without
     * `->withoutGlobalScope('company')` silently drops any platform-default
     * concept behind the active tenant's BelongsToCompany scope. This exact
     * bug has already bitten three times in Fase 8-9 (see
     * composed-knitting-dusk.md's "Modelos" section) — do not eager-load
     * this relation bare.
     *
     * @return BelongsTo<SocialSecurityConceptDefinition, $this>
     */
    public function concept(): BelongsTo
    {
        return $this->belongsTo(SocialSecurityConceptDefinition::class, 'concept_id');
    }
}
